spring:
  application:
    name: PAYMENT-SERVICE
  config:
    import:
      - "optional:configserver:http://localhost:8088"
      - "optional:configserver:http://localhost:8088/mysql-database"
#  datasource:
#    url: jdbc:mysql://localhost:3306/user_db
#    username: root
#    password: root
#  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
#    hibernate:
#      ddl-auto: create
#    show-sql: true

